server:
  port: 8080

spring:
  datasource:
    username: root
    password: wkx123
    url: jdbc:mysql://localhost:13306/Mybatis?characterEncoding=utf-8&&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.kay.demo.entity

